FROM debian:bullseye-slim

# Set Vairable
ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
	ca-certificates=20210119 \
	sudo=1.9.5p2-3 \
	curl=7.74.0-1.3+deb11u3 \
	git=1:2.30.2-1 \
	build-essential=12.9 \
	clangd=1:11.0-51+nmu5 \
	python3=3.9.2-3 \
	python3-pip=20.3.4-4+deb11u1 \
	&& rm -rf /var/lib/apt/lists/*

# Install code-server
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -fsSL https://code-server.dev/install.sh | sh

# Install Node.js
# Ignore DL3008 because version cannot be specified
# hadolint ignore=DL3008
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
	&& apt-get install -y --no-install-recommends nodejs

# Install atcoder-cli and online-judge-tools
RUN npm install -g atcoder-cli@2.2.0 \
	&& pip3 install --no-cache-dir online-judge-tools==11.5.1

# Create user "coder"
RUN useradd --create-home coder \
	&& usermod -aG sudo coder \
	&& echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Change user
USER coder

# Make config directory and working directory
RUN mkdir -p /home/coder/.config/code-server \
	&& mkdir -p /home/coder/.config/atcoder-cli-nodejs \
	&& mkdir -p /home/coder/.local/share/online-judge-tools \
	&& mkdir -p /home/coder/workspace

# Install extension "clangd"
RUN code-server --install-extension llvm-vs-code-extensions.vscode-clangd

WORKDIR /home/coder/workspace
EXPOSE 8080
VOLUME [ "/home/coder" ]

ENTRYPOINT [ "code-server", "--bind-addr", "0.0.0.0:8080", "." ]
